### ISSUE TITLE
how to use boxer?

### ISSUE THREAD

**Issue by shankha117** [chbrown/candc#1]
how do i use use the boxer , to get a DRS output in XML format for a text document..
Please help..

**Comment by chbrown** [comment]
Ah, very good question, I don't think I ever got that far myself. It might behoove you to check out https://valeriobasile.github.io/candcapi/ and/or pester the author of that site (sorry Valerio but seriously, huge props for actually getting Boxer running).

If you make any headway and could possibly contribute a `Dockerfile` or similarly easy-to-setup solution to do this, please post back... I'm sure many others would appreciate such an improvement.

**Comment by shankha117** [comment]
Well I finally got the boxer running and now able to generate DRS.
go to https://github.com/valeriobasile/learningbyreading.
Install the requirements.
install swi-prolog(REQUIRED).Then set the path to /learningbyreading-master/ext/candc

The flow is -
tokenize(./t)---->CCG(./candc)--->BOXER(./boxer)
